// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_23CV.Context;

#nullable disable

namespace ProyectoFinal_23CV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719233521_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.Property<int>("GenerosPkGenero")
                        .HasColumnType("int");

                    b.Property<int>("PeliculasPkPelicula")
                        .HasColumnType("int");

                    b.HasKey("GenerosPkGenero", "PeliculasPkPelicula");

                    b.HasIndex("PeliculasPkPelicula");

                    b.ToTable("GeneroPelicula");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Genero", b =>
                {
                    b.Property<int>("PkGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PkGenero");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            PkGenero = 1,
                            Nombre = "Acción"
                        },
                        new
                        {
                            PkGenero = 2,
                            Nombre = "Comedia"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Pelicula", b =>
                {
                    b.Property<int>("PkPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PkPelicula");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PkPelicula = 1,
                            Titulo = "Pelicula 1"
                        },
                        new
                        {
                            PkPelicula = 2,
                            Titulo = "Pelicula 2"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Pelicula_Has_Genero", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.HasKey("PeliculaId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Pelicula_Has_Genero");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            PkRol = 2,
                            Nombre = "Usuario Normal"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PkUsuario = 1,
                            FkRol = 1,
                            Nombre = "Usuario 1",
                            Password = "password1",
                            UserName = "user1"
                        },
                        new
                        {
                            PkUsuario = 2,
                            FkRol = 2,
                            Nombre = "Usuario 2",
                            Password = "password2",
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosPkGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_23CV.Entities.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasPkPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Pelicula_Has_Genero", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Genero", "Genero")
                        .WithMany("PeliculasGenero")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_23CV.Entities.Pelicula", "Pelicula")
                        .WithMany("PeliculasGenero")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoFinal_23CV.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Genero", b =>
                {
                    b.Navigation("PeliculasGenero");
                });

            modelBuilder.Entity("ProyectoFinal_23CV.Entities.Pelicula", b =>
                {
                    b.Navigation("PeliculasGenero");
                });
#pragma warning restore 612, 618
        }
    }
}
